import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID,generateKeyPairSync} from 'node:crypto';
import {GuestCredentialStore} from '../src/guest-credentials.mjs';import {nativeLogin,nativeInference} from '../src/pi-native.mjs';import {AuthStore,Network} from '../src/network.mjs';import {credentialVolume} from '../src/credential-volume.mjs';
const node={id:randomUUID(),provider:'outside-catalog',connectorProtocol:'pi_native_v2',nativeRevision:3,fields:{},connection:{kind:'custom',headerNames:['x-api-key']},maxOutputTokens:512,nativeModels:[{model:'custom-one',provider:'outside-catalog',api:'openai-completions',endpoint:'https://compatible.example.test/v1',capabilities:['coding_v1','streaming_v1','tools_v1'],contextWindowTokens:32768,maxOutputTokens:512,price:{input:1,output:2,cacheRead:1,cacheWrite:1}}]};
const frame=()=>({requestId:randomUUID(),model:'custom-one',provider:node.provider,api:'openai-completions',nativeRevision:3,endpoint:node.nativeModels[0].endpoint,messageFormat:'pi_context_v1',messages:[{role:'user',content:'synthetic',timestamp:0}],tools:[],thinking:false,maxOutputTokens:128,upstreamBudget:{inputBound:8192,reservedMicrousd:'1000000',inputMicrousdPerMillion:'1000000',outputMicrousdPerMillion:'1000000'}});
const fixture=async fn=>{const dir=await mkdtemp(join(tmpdir(),'adr-spec-fixture-'));try{await fn(dir);}finally{await rm(dir,{recursive:true,force:true});}};
test('custom Pi protocol uses actual endpoint and saved key/header without vendor allowlist',()=>fixture(async dir=>{
 const credentials=new GuestCredentialStore(dir),auth=await nativeLogin(node,'synthetic-key',undefined,{credentials,headers:{'x-api-key':'synthetic-header'}});await auth.close();const restored=await nativeLogin(node,undefined,undefined,{credentials:new GuestCredentialStore(dir)});let calls=0;
 try{const result=await nativeInference(node,restored,frame(),AbortSignal.timeout(5000),()=>{},()=>{},async(url,init)=>{calls++;assert.equal(String(url),'https://compatible.example.test/v1/chat/completions');const h=new Headers(init.headers);assert.equal(h.get('x-api-key'),'synthetic-header');assert.equal(h.get('authorization'),'Bearer synthetic-key');assert.equal(JSON.parse(init.body).model,'custom-one');return new Response([{choices:[{index:0,delta:{content:'ready'},finish_reason:'stop'}],usage:{prompt_tokens:10,completion_tokens:2,total_tokens:12}},'[DONE]'].map(x=>'data: '+(typeof x==='string'?x:JSON.stringify(x))+'\n\n').join(''),{headers:{'content-type':'text/event-stream'}});});assert.equal(result.text,'ready');assert.equal(calls,1);
 for(const patch of [{model:'not-offered'},{endpoint:'https://different.test/v1'},{nativeRevision:2},{api:'anthropic-messages'}])await assert.rejects(nativeInference(node,restored,{...frame(),...patch},AbortSignal.timeout(1000),()=>{},()=>{},()=>{throw Error('must not dispatch');}),/binding/);
 }finally{await restored.close();}assert.deepEqual(await credentials.list(),[{providerId:node.provider,type:'api_key'}]);await credentials.disconnect();assert.equal(await credentials.read(node.provider),undefined);await assert.rejects(nativeLogin(node,undefined,undefined,{credentials}),/api_key_required/);
}));
test('guest store serializes mutations and does not erase persisted auth on close',()=>fixture(async dir=>{const store=new GuestCredentialStore(dir);await store.modify('p',async()=>({type:'api_key',key:'synthetic',count:0}));await Promise.all(Array.from({length:8},()=>store.modify('p',async current=>({...current,count:current.count+1}))));assert.equal((await store.read('p')).count,8);await store.delete('p');assert.equal(await store.read('p'),undefined);}));
test('offline sign-out clears usable authentication and preserves only revocation metadata',()=>fixture(async home=>{const store=new AuthStore(home,'provider'),pair=generateKeyPairSync('ed25519'),id=randomUUID();await store.write({origin:'https://example.test',installation_id:id,access_token:'synthetic-access',refresh_token:'synthetic-refresh',refreshPending:true,publicKey:pair.publicKey.export({format:'jwk'}),privateKey:pair.privateKey.export({format:'jwk'})});let calls=0;const network=new Network({origin:'https://example.test',store,fetcher:async()=>{calls++;throw Error('offline');}});const result=await network.logout();assert.equal(result.message,'Signed out locally; server revocation unconfirmed.');assert.equal(await store.read(),null);const marker=JSON.parse(await readFile(join(await store.directory(),'revocation.json'),'utf8'));assert.equal(marker.installationId,id);assert.deepEqual(Object.keys(marker).sort(),['at','confirmed','installationId','origin']);assert.equal(calls,1);await assert.rejects(network.request('/v2/providers/me'),/login_required/);}));
test('explicit orphan repair preserves live locks and original auth state',()=>fixture(async home=>{const store=new AuthStore(home,'provider'),path=join(await store.directory(),'auth.lock');await writeFile(path,JSON.stringify({pid:process.pid}),{mode:0o600});await assert.rejects(store.repairLock(),/busy/);await writeFile(path,JSON.stringify({pid:2147483647}),{mode:0o600});assert.equal((await store.repairLock()).repaired,true);await store.withLock(async()=>store.write({scope:'marketplace:provider'}));assert.equal((await store.read()).scope,'marketplace:provider');}));
test('another account cannot resolve or create a credential volume',async()=>{let calls=0;const network={origin:'https://example.test',store:{read:async()=>({installation_id:'current'})},request:async path=>path==='/v2/providers/me'?{userId:'other'}:{id:node.id,ownerId:'owner',installationId:'current'}};await assert.rejects(credentialVolume(network,{call:async()=>{calls++;}}, {...node,ownerId:'owner'}),/not_authorized/);assert.equal(calls,0);});
test('endpoint discovery is metadata-only, deduplicates IDs and reports unavailable discovery',async()=>{const {nativeDiscover}=await import('../src/pi-native.mjs');const auth=await nativeLogin({...node,connection:{kind:'custom',headerNames:[]}},'synthetic-key');try{const result=await nativeDiscover(node,auth,AbortSignal.timeout(5000),async(url,init)=>{assert.equal(init.method,'GET');assert.equal(String(url),'https://compatible.example.test/v1/models');return Response.json({data:[{id:'custom-one'},{id:'custom-two'},{id:'custom-one'},{id:'unsafe\nlabel'}]});});assert.deepEqual(result.models,['custom-one','custom-two']);assert.equal(node.nativeModels.length,1);await assert.rejects(nativeDiscover(node,auth,AbortSignal.timeout(5000),async()=>new Response('',{status:404})),/discovery_unavailable/);}finally{await auth.close();}});

test('removing a secret header from configuration prevents sending its retained value',()=>fixture(async dir=>{const credentials=new GuestCredentialStore(dir);const original=await nativeLogin(node,'synthetic-key',undefined,{credentials,headers:{'x-api-key':'synthetic-header'}});await original.close();const changed=await nativeLogin({...node,connection:{kind:'custom',headerNames:[]}},undefined,undefined,{credentials});try{assert.deepEqual((await changed.models.getAuth(node.provider)).auth.headers,{});}finally{await changed.close();}}));

test('released guest locks tolerate contending observers without losing retained updates',()=>fixture(async dir=>{
 const store=new GuestCredentialStore(dir);await store.modify('synthetic',async()=>({type:'api_key',key:'synthetic-fixture',count:0}));
 for(let round=0;round<20;round++)await Promise.all(Array.from({length:8},()=>store.modify('synthetic',async current=>({...current,count:current.count+1}))));
 assert.equal((await store.read('synthetic')).count,160);
}));
