import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { stripTypeScriptTypes } from 'node:module';
const revision = 'd981de1229ef899957bbe968bc8dcda02a21f477';
const paths = { 'fuzzy': 'packages/tui/src/fuzzy.ts', 'truncate': 'packages/agent/src/harness/utils/truncate.ts' };
const sha = text => createHash('sha256').update(text).digest('hex');
const target = new URL('../src/vendor/pi/', import.meta.url); await mkdir(target, { recursive: true });
const lock = { version: '0.85.1', repository: 'https://github.com/earendil-works/pi', revision, adaptation: 'TypeScript type erasure only; host/credential/agent execution remains adr-cli owned.', files: {} };
for (const [name, path] of Object.entries({ ...paths, LICENSE: 'LICENSE' })) {
  const response = await fetch(`https://raw.githubusercontent.com/earendil-works/pi/${revision}/${path}`); if (!response.ok) throw Error('upstream_unavailable');
  const source = await response.text();
  const output = name === 'LICENSE' ? source : '// Generated by scripts/vendor-pi.mjs from the immutable Pi baseline.\n' + stripTypeScriptTypes(source, { mode: 'strip' });
  const filename = name === 'LICENSE' ? name : `${name}.mjs`;
  const existing = await readFile(new URL('../pi-provenance.lock.json', import.meta.url), 'utf8').then(JSON.parse).catch(e => { if (e.code === 'ENOENT') return null; throw e; });
  if (existing && (existing.files[filename]?.sourceSha256 !== sha(source) || existing.revision !== revision)) throw Error('upstream_provenance_mismatch');
  await writeFile(new URL(filename, target), output);
  lock.files[filename] = { source: path, sourceSha256: sha(source), outputSha256: sha(output) };
}
await writeFile(new URL('../pi-provenance.lock.json', import.meta.url), JSON.stringify(lock, null, 2) + '\n');
console.log('Selected Pi 0.85.1 components generated and locked');
